version: '3.7'
services:
  tourz-app:
    container_name: tourz-app
    restart: always
    build:
      dockerfile: Dockerfile.dev # The name of the docker config file
      context: .
    volumes:
      # - /app/node_modules
      - .:/app
    links:
      - mongo
      - redis
    environment:
      - REDIS_DB_URI=redis
      - REDIS_DB_PORT=6379
      - MONGO_DB_URI=mongodb://mongo:27017/tourz-dev-db
      - JWT_AUTH_SECRET=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
      - ELASTICSEARCH_HOST=elasticsearch
  mongo:
    container_name: tourz-mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
  redis:
    container_name: tourz-redis
    image: redis
    restart: always
